version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  product-service:
    build: ./backend/ProductService
    ports:
      - "5001:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy

  order-service:
    build: ./backend/OrderService
    ports:
      - "5002:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy

  payment-service:
    build: ./backend/PaymentService
    ports:
      - "5003:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
